#!/usr/bin/env python3
"""Build every Evenfire client package from the canonical provider-neutral source.

One provider-neutral source (src/evenfire/skills + adapter manifests) fans out into
three gitignored distributions: a strict Agent Plugins 1.0.0 portable package
(skills only), an OpenAI/Codex package, and a Claude Code overlay.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import stat
import sys
import tempfile
from pathlib import Path
from typing import Callable


PLUGIN_NAME = "evenfire-skills"
PLUGIN_VERSION = "0.1.0"
PLUGIN_DESCRIPTION = (
    "Skills for building on Evenfire: create plugins and MCP servers, publish to the "
    "org registry, and run/debug the stack."
)
AGENT_PLUGINS_SCHEMA = "https://agent-plugins.org/schemas/1.0.0/plugin.schema.json"
PLUGIN_AUTHOR = {"name": "Evenfire"}
PLUGIN_REPOSITORY = "https://github.com/evenfire-ai/evenfire-skills"
PLUGIN_KEYWORDS = ["agent-skills", "evenfire", "clerum", "plugin", "mcp", "workflowrecipe"]

EXPECTED_SKILLS = (
    "create-evenfire-hook",
    "create-evenfire-mcp-server",
    "create-evenfire-plugin",
    "publish-evenfire-plugin",
    "run-debug-evenfire",
)

PORTABLE_REL = Path("dist/agent-plugins/evenfire-skills")
OPENAI_REL = Path("dist/openai/evenfire-skills")
CLAUDE_REL = Path("dist/claude-code/evenfire-skills")
MARKETPLACE_REL = Path(".agents/plugins/marketplace.json")
DISTRIBUTION_PATHS = (PORTABLE_REL, OPENAI_REL, CLAUDE_REL)
REPLACEMENT_PATHS = (Path("dist"),)

GENERATED_MARKER = (
    "<!-- Generated by scripts/build_evenfire_plugins.py from src/evenfire; do not edit. -->"
)


class BuildError(RuntimeError):
    """Raised when source or staged output violates the build contract."""


def repository_root() -> Path:
    return Path(__file__).resolve().parent.parent


def load_json(path: Path) -> dict:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise BuildError(f"cannot read JSON {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise BuildError(f"expected a JSON object in {path}")
    return value


def write_text(path: Path, text: str, mode: int = 0o644) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    path.chmod(mode)


def write_json(path: Path, value: object) -> None:
    write_text(path, json.dumps(value, indent=2, ensure_ascii=False) + "\n")


def is_within(path: Path, root: Path) -> bool:
    try:
        path.resolve().relative_to(root.resolve())
    except ValueError:
        return False
    return True


def iter_tree(root: Path):
    """Yield a deterministic tree walk without traversing directory symlinks."""
    for directory, directory_names, file_names in os.walk(root, topdown=True, followlinks=False):
        directory_names.sort()
        file_names.sort()
        current = Path(directory)
        for name in tuple(directory_names):
            path = current / name
            yield path
            if path.is_symlink():
                directory_names.remove(name)
        for name in file_names:
            yield current / name


def assert_safe_source_tree(source: Path) -> None:
    if source.is_symlink():
        raise BuildError(f"source root must not be a symlink: {source}")
    if not source.is_dir():
        raise BuildError(f"missing source directory: {source}")
    for path in iter_tree(source):
        if path.is_symlink():
            raise BuildError(f"source symlinks are not supported in deterministic packages: {path}")


def copy_tree(source: Path, destination: Path) -> None:
    """Copy without following symlinks and preserve file permission bits."""
    assert_safe_source_tree(source)
    destination.mkdir(parents=True, exist_ok=True)
    for path in iter_tree(source):
        relative = path.relative_to(source)
        target = destination / relative
        if path.is_dir():
            target.mkdir(parents=True, exist_ok=True)
            target.chmod(stat.S_IMODE(path.stat().st_mode))
        elif path.is_file():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(path, target, follow_symlinks=False)
        else:
            raise BuildError(f"unsupported source entry: {path}")


def parse_skill_frontmatter(path: Path) -> tuple[str, str]:
    text = path.read_text(encoding="utf-8")
    if not text.startswith("---\n"):
        raise BuildError(f"missing YAML frontmatter in {path}")
    end = text.find("\n---\n", 4)
    if end < 0:
        raise BuildError(f"unterminated YAML frontmatter in {path}")
    frontmatter = text[4:end]
    fields: dict[str, str] = {}
    key: str | None = None
    buffer: list[str] = []
    for line in frontmatter.splitlines():
        match = re.match(r"^(name|description):\s*(.*)$", line)
        if match:
            if key is not None:
                fields[key] = " ".join(part.strip() for part in buffer).strip()
            key = match.group(1)
            buffer = [match.group(2)]
            first = match.group(2).strip()
            if first in (">-", ">", "|", "|-"):
                buffer = []
        elif key is not None and (line.startswith("  ") or line.strip() == ""):
            buffer.append(line)
        elif key is not None:
            fields[key] = " ".join(part.strip() for part in buffer).strip()
            key = None
            buffer = []
    if key is not None:
        fields[key] = " ".join(part.strip() for part in buffer).strip()
    for field_name in ("name", "description"):
        raw = fields.get(field_name, "")
        if raw.startswith(('"', "'")):
            try:
                fields[field_name] = json.loads(raw) if raw.startswith('"') else raw[1:-1]
            except json.JSONDecodeError as exc:
                raise BuildError(f"invalid quoted frontmatter in {path}: {exc}") from exc
    if not fields.get("name") or not fields.get("description"):
        raise BuildError(f"name and description are required in {path}")
    return fields["name"], fields["description"]


def add_generated_marker(text: str) -> str:
    if GENERATED_MARKER in text:
        return text
    if text.startswith("---\n"):
        end = text.find("\n---\n", 4)
        if end < 0:
            raise BuildError("cannot mark Markdown with unterminated frontmatter")
        boundary_end = end + len("\n---\n")
        return text[:boundary_end] + "\n" + GENERATED_MARKER + "\n" + text[boundary_end:]
    return GENERATED_MARKER + "\n\n" + text


def mark_markdown_tree(root: Path) -> None:
    for path in sorted(root.rglob("*.md"), key=lambda item: item.as_posix()):
        original_mode = stat.S_IMODE(path.stat().st_mode)
        write_text(path, add_generated_marker(path.read_text(encoding="utf-8")), original_mode)


def openai_yaml(metadata: dict) -> str:
    required = ("display_name", "short_description", "default_prompt")
    if any(not isinstance(metadata.get(key), str) for key in required):
        raise BuildError(f"invalid OpenAI skill metadata: {metadata}")
    lines = [
        "interface:",
        f"  display_name: {json.dumps(metadata['display_name'], ensure_ascii=False)}",
        f"  short_description: {json.dumps(metadata['short_description'], ensure_ascii=False)}",
        f"  default_prompt: {json.dumps(metadata['default_prompt'], ensure_ascii=False)}",
    ]
    if "allow_implicit_invocation" in metadata:
        value = metadata["allow_implicit_invocation"]
        if not isinstance(value, bool):
            raise BuildError("allow_implicit_invocation must be boolean")
        lines.extend(["policy:", f"  allow_implicit_invocation: {str(value).lower()}"])
    return "\n".join(lines) + "\n"


def validate_source(root: Path) -> tuple[Path, dict]:
    source_root = root / "src/evenfire"
    skills_root = source_root / "skills"
    assert_safe_source_tree(source_root)
    openai_metadata = load_json(source_root / "adapters/openai/skills.json")

    skill_dirs = tuple(sorted(path.name for path in skills_root.iterdir() if path.is_dir()))
    if skill_dirs != EXPECTED_SKILLS:
        raise BuildError(f"expected {EXPECTED_SKILLS}, found {skill_dirs}")

    names: list[str] = []
    for skill_name in skill_dirs:
        skill_file = skills_root / skill_name / "SKILL.md"
        if not skill_file.is_file():
            raise BuildError(f"missing canonical SKILL.md: {skill_file}")
        name, _ = parse_skill_frontmatter(skill_file)
        if name != skill_name:
            raise BuildError(f"frontmatter name {name!r} does not match {skill_name!r}")
        names.append(name)
    if len(names) != len(set(names)):
        raise BuildError(f"duplicate canonical skill names: {names}")

    if tuple(sorted(openai_metadata)) != EXPECTED_SKILLS:
        raise BuildError("OpenAI metadata must cover exactly the canonical skills")

    claude_adapter = source_root / "adapters/claude-code"
    if not (claude_adapter / "CLAUDE.md").is_file():
        raise BuildError("missing Claude adapter CLAUDE.md")
    return skills_root, openai_metadata


def build_skill_set(skills_root: Path, destination: Path, metadata: dict | None = None) -> None:
    for skill_name in EXPECTED_SKILLS:
        skill_destination = destination / skill_name
        copy_tree(skills_root / skill_name, skill_destination)
        if metadata is not None:
            write_text(skill_destination / "agents/openai.yaml", openai_yaml(metadata[skill_name]))
    mark_markdown_tree(destination)


def build_portable(stage_repo: Path, skills_root: Path) -> None:
    destination = stage_repo / PORTABLE_REL
    build_skill_set(skills_root, destination / "skills")
    write_json(
        destination / "plugin.json",
        {
            "$schema": AGENT_PLUGINS_SCHEMA,
            "name": PLUGIN_NAME,
            "version": PLUGIN_VERSION,
            "description": PLUGIN_DESCRIPTION,
            "author": PLUGIN_AUTHOR,
            "repository": PLUGIN_REPOSITORY,
            "keywords": PLUGIN_KEYWORDS,
        },
    )


def build_openai(stage_repo: Path, skills_root: Path, metadata: dict) -> None:
    destination = stage_repo / OPENAI_REL
    build_skill_set(skills_root, destination / "skills", metadata)
    write_json(
        destination / ".codex-plugin/plugin.json",
        {
            "name": PLUGIN_NAME,
            "version": PLUGIN_VERSION,
            "description": PLUGIN_DESCRIPTION,
            "skills": "./skills/",
        },
    )


def build_claude(stage_repo: Path, root: Path, skills_root: Path) -> None:
    destination = stage_repo / CLAUDE_REL
    adapter = root / "src/evenfire/adapters/claude-code"
    destination.mkdir(parents=True, exist_ok=True)
    shutil.copy2(adapter / "CLAUDE.md", destination / "CLAUDE.md")
    build_skill_set(skills_root, destination / ".claude/skills")
    mark_markdown_tree(destination)


def ensure_no_symlinks(root: Path) -> None:
    if root.is_symlink():
        raise BuildError(f"generated output root is a symlink: {root}")
    for path in iter_tree(root):
        if path.is_symlink():
            raise BuildError(f"generated output contains a symlink: {path}")


def validate_staged(stage_repo: Path, openai_metadata: dict) -> None:
    for relative in DISTRIBUTION_PATHS:
        if not (stage_repo / relative).exists():
            raise BuildError(f"staged build is missing {relative}")
    ensure_no_symlinks(stage_repo / "dist")

    for package in (PORTABLE_REL, OPENAI_REL):
        skills = stage_repo / package / "skills"
        found = tuple(sorted(path.name for path in skills.iterdir() if path.is_dir()))
        if found != EXPECTED_SKILLS:
            raise BuildError(f"staged {package} has incorrect skills: {found}")
        for skill_name in found:
            name, _ = parse_skill_frontmatter(skills / skill_name / "SKILL.md")
            if name != skill_name:
                raise BuildError(f"staged skill mismatch: {skill_name}: {name}")

    portable = stage_repo / PORTABLE_REL
    forbidden_paths = (".codex-plugin", ".claude", "CLAUDE.md", "AGENTS.md", "mcp.json")
    if any((portable / value).exists() for value in forbidden_paths):
        raise BuildError("portable package contains a client-specific or unsupported sidecar")
    if any(portable.glob("skills/*/agents/openai.yaml")):
        raise BuildError("portable package contains OpenAI skill metadata")

    for skill_name in EXPECTED_SKILLS:
        actual = (
            stage_repo / OPENAI_REL / "skills" / skill_name / "agents/openai.yaml"
        ).read_text(encoding="utf-8")
        if actual != openai_yaml(openai_metadata[skill_name]):
            raise BuildError(f"OpenAI metadata drift for {skill_name}")

    claude_root_entries = {path.name for path in (stage_repo / CLAUDE_REL).iterdir()}
    if claude_root_entries != {"CLAUDE.md", ".claude"}:
        raise BuildError(f"unexpected Claude distribution entries: {claude_root_entries}")


def build_staged_tree(root: Path, stage_repo: Path) -> None:
    skills_root, openai_metadata = validate_source(root)
    build_portable(stage_repo, skills_root)
    build_openai(stage_repo, skills_root, openai_metadata)
    build_claude(stage_repo, root, skills_root)
    validate_staged(stage_repo, openai_metadata)


def tree_snapshot(path: Path) -> dict[str, tuple[str, int, bytes]]:
    if path.is_symlink():
        return {".": ("symlink", 0, os.readlink(path).encode())}
    if not path.exists():
        return {}
    if path.is_file():
        return {".": ("file", stat.S_IMODE(path.stat().st_mode) & 0o111, path.read_bytes())}
    snapshot: dict[str, tuple[str, int, bytes]] = {}
    for entry in iter_tree(path):
        relative = entry.relative_to(path).as_posix()
        if entry.is_symlink():
            snapshot[relative] = ("symlink", 0, os.readlink(entry).encode())
        elif entry.is_dir():
            snapshot[relative] = ("dir", 0, b"")
        elif entry.is_file():
            snapshot[relative] = ("file", stat.S_IMODE(entry.stat().st_mode) & 0o111, entry.read_bytes())
        else:
            snapshot[relative] = ("other", 0, b"")
    return snapshot


def check_drift(root: Path, stage_repo: Path) -> list[str]:
    drift: list[str] = []
    for relative in REPLACEMENT_PATHS:
        if tree_snapshot(stage_repo / relative) != tree_snapshot(root / relative):
            drift.append(relative.as_posix())
    return drift


def assert_safe_destination(root: Path, target: Path) -> None:
    try:
        relative = target.relative_to(root)
    except ValueError as exc:
        raise BuildError(f"output target is outside the repository: {target}") from exc
    current = root
    for part in relative.parent.parts:
        current = current / part
        if current.is_symlink():
            raise BuildError(f"output parent must not be a symlink: {current}")
        if current.exists() and not current.is_dir():
            raise BuildError(f"output parent is not a directory: {current}")


def replace_outputs(root: Path, stage_repo: Path, backup_root: Path) -> None:
    backup_root.mkdir(parents=True, exist_ok=True)
    backups: dict[Path, Path] = {}
    installed: list[Path] = []
    try:
        for index, relative in enumerate(REPLACEMENT_PATHS):
            target = root / relative
            staged = stage_repo / relative
            backup = backup_root / f"{index:02d}"
            assert_safe_destination(root, target)
            target.parent.mkdir(parents=True, exist_ok=True)
            if target.exists() or target.is_symlink():
                shutil.move(str(target), str(backup))
                backups[target] = backup
            shutil.move(str(staged), str(target))
            installed.append(target)
    except Exception:
        for target in reversed(installed):
            if target.is_dir() and not target.is_symlink():
                shutil.rmtree(target)
            elif target.exists() or target.is_symlink():
                target.unlink()
        for target, backup in backups.items():
            if backup.exists() or backup.is_symlink():
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.move(str(backup), str(target))
        raise


def scratch_parent(root: Path, override: str | None) -> Path:
    configured = override or os.environ.get("CODEX_SCRATCH_ROOT")
    scratch_base = Path(configured).expanduser().resolve() if configured else Path(
        tempfile.gettempdir()
    ).resolve()
    parent = (scratch_base / root.name).resolve()
    if not is_within(parent, scratch_base):
        raise BuildError(f"task scratch path escapes root: {parent}")
    parent.mkdir(parents=True, exist_ok=True)
    probe = parent / ".write-probe"
    try:
        probe.write_text("ok", encoding="utf-8")
        probe.unlink()
    except OSError as exc:
        raise BuildError(f"scratch root is not writable: {parent}: {exc}") from exc
    return parent


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify deterministic generation and report stale local output when present",
    )
    parser.add_argument("--scratch-root", help="override CODEX_SCRATCH_ROOT for staged artifacts")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    root = repository_root()
    try:
        parent = scratch_parent(root, args.scratch_root)
        with tempfile.TemporaryDirectory(prefix="build-evenfire-plugins-", dir=parent) as temp:
            temporary = Path(temp)
            stage_repo = temporary / "repository"
            stage_repo.mkdir()
            build_staged_tree(root, stage_repo)
            if args.check:
                second_stage = temporary / "repository-second"
                second_stage.mkdir()
                build_staged_tree(root, second_stage)
                if tree_snapshot(stage_repo / "dist") != tree_snapshot(second_stage / "dist"):
                    print("independent staged builds are not byte-stable", file=sys.stderr)
                    return 1
                if (root / "dist").exists():
                    if check_drift(root, stage_repo):
                        print("local generated output is stale: dist", file=sys.stderr)
                        return 1
                    print("generated output is deterministic; local dist is current")
                else:
                    print("generated output is deterministic; no local dist exists")
                return 0
            replace_outputs(root, stage_repo, temporary / "backups")
        print("generated portable, OpenAI-native, and Claude Code distributions")
        return 0
    except (BuildError, OSError, shutil.Error) as exc:
        print(f"build failed: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
